name: CI

on:
  push:
    branches: [refactor/kms0219kms]

  pull_request:
    branches: [master]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup poetry
        run: |
          python -m pip install pip
          pip install poetry
          #add path for poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-interaction --with style

      - name: Check style with black
        run: poetry run black --check .

      - name: Check style with isort
        run: poetry run isort --check .

  type:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup poetry
        run: |
          python -m pip install pip
          pip install poetry
          #add path for poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-interaction --with type

      - name: Check type
        run: poetry run mypy
