name: Coverage Test
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          coverage run --omit="*/test*" -m unittest -v
      - uses: codecov/codecov-action@v3
